name: featurehub_client_api
version: 1.1.2
description: This is the OpenAPI client for the FeatureHub SDK. It is not likely to be used on its own.
repository: https://github.com/featurehub-io/featurehub/tree/master/sdks/dart/client-dart-api
homepage: https://www.featurehub.io
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  dio: '>=3.0.3 <4.0.0'
  openapi_dart_common: ^3.1.0
  collection: ^1.14.11
dev_dependencies:
  test: ^1.3.0
