name: openapi_migrate
version: 1.0.0
description: Intended to allow people to migrate their code to the new null safe style as an intermediary step
homepage: homepage
environment:
  sdk: '>=2.9.0 <3.0.0'
dependencies:
  collection: '^1.14.3'
  analyzer: any
  args: ^1.5.1
  yaml: ^2.2.1
  codemod: ^0.3.0
dev_dependencies:
  test: ^1.3.0
