name: mrapi
version: 1.0.0
description: OpenAPI API client
homepage: homepage
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  dio: '>=3.0.10 <4.0.0'
  openapi_dart_common: ^3.2.0
  collection: ^1.14.11
dev_dependencies:
  test: ^1.3.0
# bought to you by the folks from FeatureHub https://featurehub.io
