name: featurehub_client_sdk
version: 1.0.0
description: Client SDK for FeatureHub
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  dio: '>=3.0.3 <4.0.0'
  eventsource: ^0.2.3
  collection: ^1.14.11
  logging: ^0.11.4
  featurehub_client_api:
    path: ../client-dart-api
dev_dependencies:
  test: ^1.3.0
