name: featurehub_client_sdk
version: 1.2.0
description: Client SDK for FeatureHub
repository: https://github.com/featurehub-io/featurehub/tree/master/sdks/dart/client-dart-sdk
homepage: https://www.featurehub.io
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  dio: ^4.0.0
#  featurehub_sse_client: ^1.0.0
  featurehub_sse_client:
    path: ../dart-eventsource
  collection: ^1.15.0
  logging: ^1.0.1
  rxdart: ^0.26.0
#  featurehub_client_api: ^1.1.2
  featurehub_client_api:
    path: ../client-dart-api
  openapi_dart_common: ^4.0.0-prev1
dev_dependencies:
  test: ^1.16.8
#  test_coverage: ^0.4.2
  mocktail: 0.1.1
  pedantic: ^1.11.0
