name: featurehub_client_sdk
version: 1.1.1
description: Client SDK for FeatureHub
repository: https://github.com/featurehub-io/featurehub/tree/master/sdks/dart/client-dart-sdk
homepage: https://www.featurehub.io
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  dio: '>=3.0.3 <4.0.0'
  featurehub_sse_client: ^1.0.0
  collection: ^1.14.11
  logging: ^0.11.4
  rxdart: ^0.24.1
  featurehub_client_api: ^1.1.1
#  featurehub_client_api:
#    path: ../client-dart-api
  openapi_dart_common: ^3.1.0
dev_dependencies:
  test: ^1.3.0
  test_coverage: ^0.4.2
  mockito: ^4.1.1
  pedantic: ^1.9.0
