version: '3.1'

services:
  party-server:
    image: featurehub/party-server:1.1
    restart: always
    volumes:
      - featurehub-h2-data:/db
    ports:
      - 8085:8085
volumes:
  featurehub-h2-data:
